apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-argocd
  template:
    metadata:
      labels:
        app: nginx-argocd
    spec:
      containers:
      - name: nginx-argocd
        image: nginx
        ports:
        - containerPort: 80
